# Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1,2,3,5,8,13,21,34,55,89,⋯
# By considering the terms in the Fibonacci sequence whose values do not exceed N, find the sum of the even-valued terms.
# 
# Input Format 
# First line contains T, followed by T lines each containing N.
# 
# Output Format 
# Print the required answer for each test case.
# 
# Constraints 
# 1<=T<=10^5 
# 10<=N<=4×10^16
# 
# Sample Input
# 2
# 10
# 100
# 
# Sample Output
# 10
# 44
#
# http://en.wikipedia.org/wiki/Fibonacci_number
#

def fibonacci(n)
  fi = (1 + Math.sqrt(5)) / 2
  psi = 1 - fi
  return ((fi**n - psi**n) / Math.sqrt(5)).to_i
end

def sum_of_even_fibonacci(number)
  index = 3                   # at index % 3 == 0 there are always even fibonacci numbers
  result = 0
  num = fibonacci(index)
  while num <= number
    result += num
    index += 3
    num = fibonacci(index)
  end
  return result
end

def sum_of_even_fibonacci_naive(number)
  result = 0
  a = 0
  b = 1
  while b < number
    temp = a + b
    a = b
    b = temp
    result += a if a % 2 == 0
  end
  return result
end

gets.chomp.to_i.times do
  input = gets.chomp.to_i
  puts sum_of_even_fibonacci_naive(input)
end
