package projecteuler;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/**
 * <b>Project Euler #12: Highly divisible triangular number</b>
 * <p>
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7'th triangle number would be 1+2+3+4+5+6+7=28. The first ten terms
 * would be:
 * </p>
 * <p>
 * 1,3,6,10,15,21,28,36,45,55,...
 * </p>
 * <p>
 * Let us list the factors of the first seven triangle numbers:
 * </p>
 * <p>
 * 1: 1 <br>
 * 3: 1,3 <br>
 * 6: 1,2,3,6 <br>
 * 10: 1,2,5,10 <br>
 * 15: 1,3,5,15 <br>
 * 21: 1,3,7,21 <br>
 * 28: 1,2,4,7,14,28
 * </p>
 * <p>
 * We can see that 28 is the first triangle number to have over five divisors.
 * </p>
 * <p>
 * What is the value of the first triangle number to have over N divisors?
 * </p>
 * <p>
 * Input<br>
 * First line T, the number of testcases. <br>
 * Each testcase consists of N in one line.
 * </p>
 * <p>
 * Output<br>
 * For each testcase, print the required answer in one line.
 * </p>
 * <p>
 * Constraints<br>
 * 1<=T<=10<br>
 * 1<=N<=10^3
 * </p>
 * 
 * @author Pidanic
 *
 */
public class HighlyDivisibleTriangularNumber
{
	// urobit celociselny rozklad na prvocisla
	// (exp_na_prvocisle_1 + 1) * (exp_na_prvocisle_2 + 1) * ... *
	// (exp_na_prvocisle_n + 1)
	public static void main(String[] args)
	{
		Scanner scanner = new Scanner(System.in);
		List<Integer> primes = eratosthenes(10000000);

		int tests = Integer.parseInt(scanner.nextLine());
		for (int i = 0; i < tests; i++)
		{
			int num = 0;
			int div = 0;
			int divisors = Integer.parseInt(scanner.nextLine());
			outer: for (int number = 1; number < Integer.MAX_VALUE; number++)
			{
				int counter = 1;
				num += number;
				int n = num;
				for (int j = 0; j < primes.size() && div < n; j++)
				{
					div = primes.get(j);
					int exp = 0;
					while (n % div == 0)
					{
						exp++;
						n /= div;
					}
					counter *= (exp + 1);
					if (counter > divisors)
					{
						System.out.println(num);
						break outer;
					}
				}
			}
		}
		scanner.close();
	}

	private static List<Integer> eratosthenes(int number)
	{
		boolean[] array = new boolean[number + 1];
		for (int i = 0; i < array.length; i++)
		{
			array[i] = true;
		}
		List<Integer> primes = new ArrayList<Integer>();
		for (int i = 2; i < array.length; i++)
		{
			if (array[i])
			{
				int j = i;
				while (i * j >= 0 && i * j < array.length)
				{
					array[i * j] = false;
					j++;
				}
				primes.add(i);
			}
		}
		return primes;
	}
}
